config/routes.rb
Rails.application.routes.draw do
  get 'events/create' => 'events#create'

  get 'home/friend'
  get 'home/edit/:id' => 'home#edit'
  get 'home/update/:id' => 'home#update'
  get 'home/destroy/:id' => 'home#destroy'

  post '/friendships' => 'friendships#create'
  delete '/friendships' => 'friendships#destroy'

  resources :events, only: [:create, :destroy]
  devise_for :users

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(current_user.id)
    @events = @user.events
  end

  def destroy
    @events = Event.find(params[:id])

    @events.destroy

    redirect_to '/'
  end

  def edit
    @events = Event.find(params[:id])
  end

  def update
    @events = Event.find(params[:id])
    @events.content = params[:content]
    @events.start_time = params[:start_time]
    @events.end_time = params[:end_time]
    @events.place = params[:place]

    @events.save

    redirect_to '/'
  end

  def friend

    if params[:all]
      @friends = User.find(current_user.id).friends
      @a = Event.none
      @friends.each do |f|
        b = Event.where(user_id: f.id)
        @a = @a.or(b)
      end
      @a = @a.order(created_at: :desc)
    else
      if params[:search]
        @keyword = params[:keyword]
        @search_users = User.where("email like ?", "%#{@keyword.to_s}%")
        if params[:id].present?
          @events = User.find(params[:id]).events
        end
        @friends = User.find(current_user.id).friends
      else
        if params[:id].present?
          @events = User.find(params[:id]).events
        end
        @friends = User.find(current_user.id).friends
      end
    end




  end

end

app/helpers/home_helper.rb
module HomeHelper
  def is_friend?(current_user_id, friend_id)
    a = Friendship.where(user_id: current_user_id, friend_id: friend_id)
    if a.blank?
      false
    else
      true
    end
  end
end

app/views/home/edit.html.erb
<!-- Header -->
<div id="header">

  <div class="top">

    <!-- Logo -->
    <div id="logo">
      <span class="image avatar48"><%= image_tag("avatar.jpg") %></span>
      <a href="/"><h1 id="title">toDook</h1></a>
      <p>Todo List with SNS</p>
      <p><%= current_user.email %> <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete %></p>
    </div>

    <!-- Nav -->
    <nav id="nav">
      <ul>
        <li><a href="#top" id="top-link" class="skel-layers-ignoreHref">To Do</a></li>
        <li><a href="#todo" id="portfolio-link" class="skel-layers-ignoreHref">To Do List</a></li>
        <li><a href="/home/friend/#friends" id="contact-link" class="skel-layers-ignoreHref">Friends</a></li>
        <li></li>
      </ul>
    </nav>

  </div>

</div>

<!-- Main -->
<div id="main">

  <!-- Intro -->
  <section id="top" class="one cover">
    <div class="container">

      <header class="ppp">
        <h3 class="alt"><strong class="logos">Hi! I'm toDook</strong></h3>
        <p>Share your schedule with your friends</p>
      </header>

      <footer>
        <form method="get" action="/home/update/<%= @events.id %>">
          <article class="row">

            <div class="12u$"><label for="filter-date">Things todo</label><input type="text" name="content" value="<%= @events.content %>" /></div>

            <article class="item1">
              <label for="filter-date">Start time</label>
              <input id="startdatetimepicker1" type="text" name="start_time" value="<%= @events.start_time %>">
            </article>

            <article class="item1">
              <label for="filter-date">End time</label>
              <input id="enddatetimepicker1" type="text" name="end_time" value="<%= @events.end_time %>">
            </article>

            <article class="item1">
              <label for="filter-date">Place</label>
              <input type="text" name="place" value="<%= @events.place %>">
            </article>
            <article class="item1">
              <label for="filter-date"></label>
              <button type="submit" value="edit">edit</button>
            </article>

          </article>
        </form>

      </footer>

    </div>
  </section>

  </main>
</div>

<!-- Footer -->
<div id="footer" class="one cover">

  <!-- Copyright -->
  <ul class="copyright">
    <li>&copy; toDook. All rights reserved.</li>
    <li>LIKELION with INHA</li>
  </ul>

</div>
<script>
    jQuery('#startdatetimepicker').datetimepicker();
    jQuery('#enddatetimepicker').datetimepicker();
</script>

app/views/home/friend.html.erb
<!-- Header -->
<div id="header">

  <div class="top">

    <!-- Logo -->
    <div id="logo">
      <span class="image avatar48"><%= image_tag("avatar.jpg") %></span>
      <a href="/"><h1 id="title">toDook</h1></a>
      <p><%= current_user.email %> <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete %></p>
    </div>

    <!-- Nav -->
    <nav id="nav">
      <ul>
        <li><a href="/#top" id="portfolio-link" class="skel-layers-ignoreHref">To Do</a></li>
        <li><a href="/home/friend/#friends" id="contact-link" class="skel-layers-ignoreHref">Friends</a></li>
      </ul>
    </nav>

  </div>

</div>

<!-- Main -->
<div id="main">

  <!-- Friends -->
  <section id="friends" class="one cover">
    <div class="container">

      <header>
        <h2>User search</h2>
      </header>

      <%= form_tag(home_friend_path, method: :get) do %>
          <%= hidden_field_tag(:search, true) %>
          <%= hidden_field_tag(:id, params[:id]) %>
          <%= search_field_tag(:keyword, '') %>
          <input type="submit" value="search" class="btn btn-secondary">
      <% end %>

      <br/>

      <% if @search_users.present? %>
          <% @search_users.each do |su| %>
              <% if current_user.id == su.id %>

              <% else %>
                  <%= link_to "#{su.email}", home_friend_path(id: su.id, search: params[:search], keyword: params[:keyword]) %>
              <% end %>
              <% unless current_user.id == su.id %>
                  <% if is_friend?(current_user.id, su.id) %>
                      <%= link_to '친구삭제', friendships_path(friend_id: su.id), method: :delete %>
                  <% else %>
                      <%= link_to '친구추가', friendships_path(friend_id: su.id), method: :post %>
                  <% end %>
              <% end %>

              <br>
          <% end %>
      <% end %>

      <br/>

      <h4>Friends list</h4>
      <% @friends.each do |f| %>
          <%= link_to "#{f.email}", home_friend_path(id: f.id) %> <%= link_to '친삭', friendships_path(user_id: current_user.id, friend_id: f.id), method: :delete %>
          <br>
      <% end %>

      <%= link_to 'see all todos of my firends', home_friend_path(all: true) %>
    </div>
  </section>


  <% if params[:id].present? or params[:all].present? %>
      <!-- Todo list -->
      <section id="todo" class="one cover">
        <div class="container">

          <header>
            <h2>Friends To do</h2>
          </header>

          <% if params[:all].present? %>
              <% if @a.present? %>
                  <div class="row">
                    <% @a.each do |all_event| %>

                        <div class="4u 12u$(mobile)">
                          <% if is_friend?(current_user.id, all_event.user_id) %>
                              <%= link_to '공유', events_path(content: all_event.content, start_time: all_event.start_time, end_time: all_event.end_time, place: all_event.place), method: :post %>
                          <% end %>
                          <div class="post-it-note">
                            <p class="pp"><%= all_event.content %></p>
                            <b class="pa"><%= all_event.start_time.month %>/<%= all_event.start_time.day %> <% if all_event.start_time.hour < 10 %>0<% end %><%= all_event.start_time.hour %>:<% if all_event.start_time.min < 10 %>0<% end %><%= all_event.start_time.min %>
                              ~ <%= all_event.end_time.month %>/<%= all_event.end_time.day %> <% if all_event.end_time.hour < 10 %>0<% end %><%= all_event.end_time.hour %>:<% if all_event.end_time.min < 10 %>0<% end %><%= all_event.end_time.min %>
                              <br/><%= all_event.place %><br/></b>
                          </div>
                        </div>
                    <% end %>
                  </div>
              <% elsif @friends.blank? %>
                  <p>친구가 없어요...</p>
              <% else %>
                  <p>친구들의 일정이 없어요</p>
              <% end %>

          <% else %>

              <% if @events.present? %>
                  <div class="row">
                    <% @events.each do |event| %>

                        <div class="4u 12u$(mobile)">
                          <% if is_friend?(current_user.id, event.user_id) %>
                              <%= link_to '공유', events_path(content: event.content, start_time: event.start_time, end_time: event.end_time, place: event.place), method: :post %>
                          <% end %>
                          <div class="post-it-note">
                            <p class="pp"><%= event.content %></p>
                            <p class="pa"><%= event.start_time.month %>/<%= event.start_time.day %> <% if event.start_time.hour < 10 %>0<% end %><%= event.start_time.hour %>:<% if event.start_time.min < 10 %>0<% end %><%= event.start_time.min %>
                              ~ <%= event.end_time.month %>/<%= event.end_time.day %> <% if event.end_time.hour < 10 %>0<% end %><%= event.end_time.hour %>:<% if event.end_time.min < 10 %>0<% end %><%= event.end_time.min %>
                              <br/><%= event.place %><br/></p>
                          </div>

                        </div>
                    <% end %>
                  </div>
              <% else %>
                  <p>친구의 일정이 없어요</p>
              <% end %>

          <% end %>

        </div>
      </section>
  <% end %>

</div>

<!-- Footer -->
<div id="footer">

  <!-- Copyright -->
  <ul class="copyright">
    <li>&copy; toDook. All rights reserved.</li>
    <li>LIKELION with INHA</li>
  </ul>

</div>
<script>
    jQuery('#startdatetimepicker').datetimepicker();
    jQuery('#enddatetimepicker').datetimepicker();
</script>

app/views/home/index.html.erb
<!-- Header -->
<div id="header">

  <div class="top">

    <!-- Logo -->
    <div id="logo">
      <span class="image avatar48"><%= image_tag("avatar.jpg") %></span>
      <a href="/"><h1 id="title">toDook</h1></a>
      <p><%= current_user.email %> <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete %></p>
    </div>

    <!-- Nav -->
    <nav id="nav">
      <ul>
        <li><a href="#top" id="top-link" class="skel-layers-ignoreHref">To Do</a></li>
        <li><a href="#todo" id="portfolio-link" class="skel-layers-ignoreHref">To Do List</a></li>
        <li><a href="/home/friend/#friends" id="contact-link" class="skel-layers-ignoreHref">Friends</a></li>
        <li></li>
      </ul>
    </nav>

  </div>

</div>

<!-- Main -->
<div id="main">

  <!-- Intro -->
  <section id="top" class="one cover">
    <div class="container">

      <header class="ppp">
        <h3 class="alt"><strong class="logos">Hi! I'm toDook</strong></h3>
        <p>Share your schedule with your friends</p>
      </header>

      <footer>
        <form method="get" action="events/create">
          <article class="row">

          <div class="12u$"><label for="filter-date">Things todo</label><input type="text" name="content" placeholder="" /></div>

            <article class="item1">
               <label for="filter-date">Start time</label>
               <input id="startdatetimepicker" type="text" name="start_time">
            </article>

            <article class="item1">
              <label for="filter-date">End time</label>
              <input id="enddatetimepicker" type="text" name="end_time">
            </article>

            <article class="item2">
              <label for="filter-date">Place</label>
              <input type="text" name="place">
            </article>
            
            <div class="container">
              <input type="submit" value="Post toDook"/>
            </div>

          </article>
        </form>
      </footer>
    </div>
  </section>
  <!-- Portfolio -->
  <section id="todo" class="one cover">
    <div class="container">

      <header>
        <h2>To Do List</h2>
      </header>

      <% if @events.present? %>
          <div class="row">
            <% @events.each do |event| %>
                <div class="4u 12u$(mobile)" >
                  <a href="home/edit/<%= event.id %>">수정</a>
                  <a href="home/destroy/<%= event.id %>">삭제</a>

                    <div class="post-it-note">
                      <p class="pp"><%= event.content %></p>
                      <b class="pa"><%= event.start_time.month %>/<%= event.start_time.day %> <% if event.start_time.hour < 10 %>0<% end %><%= event.start_time.hour %>:<% if event.start_time.min < 10 %>0<% end %><%= event.start_time.min %>
                        ~ <%= event.end_time.month %>/<%= event.end_time.day %> <% if event.end_time.hour < 10 %>0<% end %><%= event.end_time.hour %>:<% if event.end_time.min < 10 %>0<% end %><%= event.end_time.min %>
                        <br/><%= event.place %><br/></b>
                    </div>
                </div>
            <% end %>
      <% else %>
          <a href="#">새로운 todo를 추가해 주세요!</a>
      <% end %>

      </div>
    </div>
  </section>


    </div>
  </main>
</div>

<!-- Footer -->
<div id="footer" class="one cover">

  <!-- Copyright -->
  <ul class="copyright">
    <li>&copy; toDook. All rights reserved.</li>
    <li>LIKELION with INHA</li>
  </ul>

</div>
<script>
    jQuery('#startdatetimepicker').datetimepicker();
    jQuery('#enddatetimepicker').datetimepicker();
</script>